version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
          - 'astro-*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'globals'
          - 'astro-eslint-parser'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-*'
      playwright:
        patterns:
          - '@playwright/*'
      other-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
